// cseData.ts
export const cseCurriculum = [
  { code: 'MAT1102', name: 'DIFFERENTIAL CALCULUS & CO-ORDINATE GEOMETRY' },
  { code: 'PHY1101', name: 'PHYSICS 1' },
  { code: 'PHY1102', name: 'PHYSICS 1 LAB' },
  { code: 'ENG1101', name: 'ENGLISH READING SKILLS & PUBLIC SPEAKING' },
  { code: 'CSC1101', name: 'INTRODUCTION TO COMPUTER STUDIES' },
  { code: 'CSC1103', name: 'INTRODUCTION TO PROGRAMMING LAB' },
  { code: 'CSC1102', name: 'INTRODUCTION TO PROGRAMMING' },
  { code: 'CSC1204', name: 'DISCRETE MATHEMATICS' },
  {
    code: 'MAT1205',
    name: 'INTEGRAL CALCULUS & ORDINARY DIFFERENTIAL EQUATIONS',
  },
  { code: 'CSC1205', name: 'OBJECT ORIENTED PROGRAMMING 1' },
  { code: 'PHY1203', name: 'PHYSICS 2' },
  { code: 'PHY1204', name: 'PHYSICS 2 LAB' },
  { code: 'ENG1202', name: 'ENGLISH WRITING SKILLS & COMMUNICATIONS' },
  { code: 'COE2101', name: 'INTRODUCTION TO ELECTRICAL CIRCUITS' },
  { code: 'COE2102', name: 'INTRODUCTION TO ELECTRICAL CIRCUITS LAB' },
  { code: 'CHEM1101', name: 'CHEMISTRY' },
  { code: 'MAT2101', name: 'COMPLEX VARIABLE, LAPLACE & Z-TRANSFORMATION' },
  { code: 'CSC2108', name: 'INTRODUCTION TO DATABASE' },
  { code: 'EEE2104', name: 'ELECTRONIC DEVICES LAB' },
  { code: 'BBA1102', name: 'PRINCIPLES OF ACCOUNTING' },
  { code: 'EEE2103', name: 'ELECTRONIC DEVICES' },
  { code: 'CSC2106', name: 'DATA STRUCTURE' },
  { code: 'CSC2107', name: 'DATA STRUCTURE LAB' },
  { code: 'BAE2101', name: 'COMPUTER AIDED DESIGN & DRAFTING' },
  { code: 'CSC2211', name: 'ALGORITHMS' },
  { code: 'MAT2202', name: 'MATRICES, VECTORS, FOURIER ANALYSIS' },
  { code: 'CSC2210', name: 'OBJECT ORIENTED PROGRAMMING 2' },
  { code: 'CSC2209', name: 'OBJECT ORIENTED ANALYSIS AND DESIGN' },
  { code: 'BAS2101', name: 'BANGLADESH STUDIES' },
  { code: 'EEE3101', name: 'DIGITAL LOGIC AND CIRCUITS' },
  { code: 'EEE3102', name: 'DIGITAL LOGIC AND CIRCUITS LAB' },
  { code: 'MAT3103', name: 'COMPUTATIONAL STATISTICS AND PROBABILITY' },
  { code: 'CSC3113', name: 'THEORY OF COMPUTATION' },
  { code: 'ECO3150', name: 'PRINCIPLES OF ECONOMICS' },
  { code: 'ENG2103', name: 'BUSINESS COMMUNICATION' },
  { code: 'MAT3101', name: 'NUMERICAL METHODS FOR SCIENCE AND ENGINEERING' },
  { code: 'COE3103', name: 'DATA COMMUNICATION' },
  { code: 'COE3104', name: 'MICROPROCESSOR AND EMBEDDED SYSTEMS' },
  { code: 'CSC3112', name: 'SOFTWARE ENGINEERING' },
  { code: 'CSC3217', name: 'ARTIFICIAL INTELLIGENCE AND EXPERT SYSTEM' },
  { code: 'COE3206', name: 'COMPUTER NETWORKS' },
  { code: 'COE3205', name: 'COMPUTER ORGANIZATION AND ARCHITECTURE' },
  { code: 'CSC3214', name: 'OPERATING SYSTEM' },
  { code: 'CSC3215', name: 'WEB TECHNOLOGIES' },
  { code: 'EEE2216', name: 'ENGINEERING ETHICS' },
  { code: 'CSC3216', name: 'COMPILER DESIGN' },
  { code: 'CSC4118', name: 'COMPUTER GRAPHICS' },
  { code: 'CSC4197', name: 'RESEARCH METHODOLOGY' },
  { code: 'MGT3202', name: 'ENGINEERING MANAGEMENT' },
];
