export const nsuCseCurriculum = [
  // Core & GenEd
  { name: 'ENG 102 Introduction to Composition' },
  { name: 'ENG 103 Intermediate Composition' },
  { name: 'ENG 111 Public Speaking' },
  { name: 'MAT 116 Pre-Calculus' },
  { name: 'MAT 120 Calculus-I' },
  { name: 'MAT 125 Linear Algebra' },
  { name: 'MAT 130 Calculus II' },
  { name: 'PHY 107 Physics I' },
  { name: 'PHY 108 Physics II' },
  { name: 'CSE 115 Programming Language I' },
  { name: 'CSE 173 Discrete Mathematics' },
  { name: 'CSE 215 Programming Language II' },
  { name: 'CSE 225 Data Structures and Algorithms' },
  { name: 'CSE 231 Digital Logic design' },
  { name: 'CSE 311 Database Systems' },
  { name: 'CSE 323 Operating Systems Design' },
  { name: 'CSE 327 Software Engineering' },
  { name: 'CSE 331 Microprocessor Interfacing' },
  { name: 'CSE 332 Computer Organization and Architecture' },
  { name: 'CSE 373 Design and Analysis of Algorithms' },
  { name: 'CSE 425 Concepts of Programming Language' },
  { name: 'CSE 299 Junior Design Course' },
  { name: 'CSE 499A Senior Design I' },
  { name: 'CSE 499B Senior Design II' },
  // Elective Trails
  { name: 'CSE 440 Artificial Intelligence' },
  { name: 'CSE 445 Machine Learning' },
  { name: 'CSE 417 Numerical Methods' },
  { name: 'CSE 482 Internet and Web Technology' },
];
