export const nsuPharCurriculum = [
  { name: 'PHR 110 Introduction to Pharmacy' },
  { name: 'PHR 112 Statistics in Pharmaceutical Sciences' },
  { name: 'PHR 113 Pharmacognosy' },
  { name: 'PHR 114 Organic Pharmacy-I' },
  { name: 'PHR 120 Inorganic Pharmacy' },
  { name: 'PHR 121 Human Physiology-I' },
  { name: 'PHR 122 Organic Pharmacy -II' },
  { name: 'PHR 123 Physical Pharmacy-I' },
  { name: 'PHR 124 Pharmaceutical Microbiology-I' },
  { name: 'PHR 210 Physical Pharmacy-II' },
  { name: 'PHR 211 Human Physiology-II' },
  { name: 'PHR 212 Pharmaceutical Technology-I' },
  { name: 'PHR 213 Biochemistry & Cell Biology' },
  { name: 'PHR 214 Pharmacology & Clinical Pharmacy-I' },
  { name: 'PHR 215 Medicinal Chemistry-I' },
  { name: 'PHR 221 Pharmaceutical Technology-II' },
  { name: 'PHR 224 Pharmaceutical Analysis-I' },
  { name: 'PHR 225 Basic Pathology & Toxicology' },
  { name: 'PHR 310 Pharmaceutical Technology-|||' },
  { name: 'PHR 428 Quality Assurance & Quality Control' },
  { name: 'PHR 515 Hospital and Community Pharmacy' },
];
