export const pharmacyCurriculum = [
  { code: 'CSC1105', name: 'COMPUTER FUNDAMENTALS' },
  { code: 'ENG1101', name: 'ENGLISH READING SKILLS & PUBLIC SPEAKING' },
  { code: 'BAS2101', name: 'BANGLADESH STUDIES' },
  { code: 'PHA1101', name: 'INTRODUCTION TO PHARMACY' },
  { code: 'PHA1102', name: 'PHARMACOGNOSY & NUTRACEUTICALS' },
  { code: 'PHA1103', name: 'PHARMACOGNOSY & NUTRACEUTICALS LAB' },
  { code: 'CSC1106', name: 'COMPUTER FUNDAMENTALS LAB' },
  { code: 'PHA1204', name: 'HUMAN ANATOMY & PHYSIOLOGY-I' },
  { code: 'PHA1205', name: 'INORGANIC PHARMACY I' },
  { code: 'PHA1206', name: 'INORGANIC PHARMACY I LAB' },
  { code: 'PHA1207', name: 'ORGANIC PHARMACY-I' },
  { code: 'PHA1208', name: 'ORGANIC PHARMACY-I LAB' },
  { code: 'PHA1209', name: 'PHYSICAL PHARMACY' },
  { code: 'PHA1210', name: 'PHYSICAL PHARMACY LAB' },
  { code: 'PHA1211', name: 'PHARMACEUTICAL STATISTICS' },
  { code: 'PHA1000', name: 'VIVA VOCE-1' },
  { code: 'PHA2101', name: 'INORGANIC PHARMACY II' },
  { code: 'PHA2102', name: 'INORGANIC PHARMACY II LAB' },
  { code: 'PHA2103', name: 'ORGANIC PHARMACY-II' },
  { code: 'PHA2104', name: 'ORGANIC PHARMACY-II LAB' },
  { code: 'PHA2105', name: 'HUMAN ANATOMY & PHYSIOLOGY-II' },
  { code: 'PHA2106', name: 'HUMAN ANATOMY & PHYSIOLOGY-II LAB' },
  { code: 'PHA2107', name: 'PHARMACEUTICAL MICROBIOLOGY-I' },
  { code: 'PHA2108', name: 'PHARMACEUTICAL MICROBIOLOGY-I LAB' },
  { code: 'PHA2109', name: 'PHARMACOLOGY-I' },
  { code: 'PHA2210', name: 'HUMAN ANATOMY & PHYSIOLOGY-III' },
  { code: 'PHA2211', name: 'HUMAN ANATOMY & PHYSIOLOGY-III LAB' },
  { code: 'PHA2212', name: 'GMP & PHARMACEUTICAL INDUSTRIAL PRACTICE' },
  { code: 'PHA2213', name: 'PHARMACEUTICAL MICROBIOLOGY-II' },
  { code: 'PHA2214', name: 'PHARMACEUTICAL MICROBIOLOGY-II LAB' },
  { code: 'PHA2215', name: 'PHARMACEUTICAL DOSAGE FORM-I' },
  { code: 'PHA2216', name: 'PHARMACEUTICAL DOSAGE FORM-I LAB' },
  { code: 'PHA2217', name: 'BIOCHEMISTRY AND MOLECULAR BIOLOGY' },
  { code: 'PHA2218', name: 'BIOCHEMISTRY AND MOLECULAR BIOLOGY LAB' },
  { code: 'PHA2000', name: 'VIVA VOCE-2' },
  { code: 'PHA3101', name: 'PHARMACEUTICAL ENGINEERING-I' },
  { code: 'PHA3102', name: 'PHARMACEUTICAL DOSAGE FORM-II' },
  { code: 'PHA3103', name: 'PHARMACEUTICAL DOSAGE FORM-II LAB' },
  { code: 'PHA3104', name: 'CLINICAL PHARMACY' },
  { code: 'PHA3105', name: 'PHARMACY PRACTICE-I' },
  { code: 'PHA3106', name: 'PHARMACEUTICAL ANALYSIS-I' },
  { code: 'PHA3107', name: 'PHARMACEUTICAL ANALYSIS-I LAB' },
  { code: 'PHA3108', name: 'PHARMACOLOGY-II' },
  { code: 'PHA3109', name: 'PHARMACOLOGY-II LAB' },
  { code: 'PHA3210', name: 'PHARMACEUTICAL DOSAGE FORM-III' },
  { code: 'PHA3211', name: 'PHARMACEUTICAL DOSAGE FORM-III LAB' },
  { code: 'PHA3212', name: 'PHARMACOLOGY-III' },
  { code: 'PHA3213', name: 'PHARMACOLOGY-III LAB' },
  { code: 'PHA3214', name: 'MEDICINAL CHEMISTRY-I' },
  { code: 'PHA3215', name: 'PHARMACEUTICAL ANALYSIS-II' },
  { code: 'PHA3216', name: 'PHARMACEUTICAL ANALYSIS-II LAB' },
  { code: 'PHA3217', name: 'PHARMACEUTICAL ENGINEERING-II' },
  { code: 'PHA3218', name: 'RESEARCH METHODOLOGY [PHA]' },
  { code: 'PHA3000', name: 'VIVA VOCE-3' },
  { code: 'PHA4101', name: 'BIOPHARMACEUTICS & CLINICAL PHARMACOKINETIC-I' },
  { code: 'PHA4102', name: 'PHARMACEUTICAL MARKETING & MANAGEMENT' },
  { code: 'PHA4103', name: 'PHARMACOLOGY-IV' },
  { code: 'PHA4104', name: 'ADVANCED PHARMACEUTICAL ANALYSIS' },
  { code: 'PHA4105', name: 'MEDICINAL CHEMISTRY-II' },
  { code: 'PHA4106', name: 'MEDICINAL CHEMISTRY-II LAB' },
  { code: 'PHA4107', name: 'COSMETOLOGY' },
  { code: 'PHA4108', name: 'COSMETOLOGY LAB' },
  { code: 'PHA4109', name: 'PHARMACEUTICAL INDUSTRIAL TRAINING' },
  { code: 'PHA4000', name: 'VIVA VOCE-4' },
  { code: 'PHA4210', name: 'BASIC PATHOLOGY & TOXICOLOGY' },
  { code: 'PHA4211', name: 'BASIC PATHOLOGY & TOXICOLOGY LAB' },
  { code: 'PHA4212', name: 'BIOPHARMACEUTICS & CLINICAL PHARMACOKINETIC-II' },
  {
    code: 'PHA4213',
    name: 'BIOPHARMACEUTICS & CLINICAL PHARMACOKINETIC-II LAB',
  },
  { code: 'PHA4214', name: 'PHARMACEUTICAL REGULATORY AFFAIRS' },
  { code: 'PHA4215', name: 'PHARMACY PRACTICE-II' },
  { code: 'PHA4216', name: 'PHARMACEUTICAL BIOTECHNOLOGY' },
  { code: 'PHA4217', name: 'PROJECT & DISSERTATION' },
];
